name: Deploy naekaracubae-scraping

on:
  pull_request:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_zip:
    name: deploy lambda function from zip
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.16.4
      - name: Build binary
        run: |
          GOOS=linux go build -v -a -o main main.go && zip naekaracubae-scraping.zip main
      - name: deploy to lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: GobbyIsntFree-dev-developerilbo
          zip_file: naekaracubae-scraping.zip
